spring:
  datasource:
    url: jdbc:mysql://localhost:3306/liar_bar?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: czx..2288
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 443                     # 改成 8443 或者 443
  servlet:
    context-path: /api
  ssl:
    enabled: true
    certificate: classpath:certs/server.crt
    certificate-private-key: classpath:certs/server.key
# Netty WebSocket配置
netty:
  websocket:
    # WebSocket服务器端口
    port: 8090
    # WebSocket路径
    path: /api/ws
    # Boss线程数（建议设置为1）
    boss-threads: 1
    # Worker线程数（0表示使用CPU核心数的2倍）
    worker-threads: 0

logging:
  level:
    root: info
    com.lb: debug
